services:
    db:
        image: container-registry.oracle.com/database/free:latest-lite
        ports:
            - "1521:1521"
        environment:
          APP_USER: ${DB_USERNAME}
          APP_USER_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./var/oracle-data:/opt/oracle/oradata
            - ./deploy/oracle/startup:/opt/oracle/scripts/startup