services:
    db:
        build: src/db
        ports:
            - "1521:1521"
        environment:
          APP_USER: ${DB_USERNAME}
          APP_USER_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./var/oracle-data:/opt/oracle/oradata
#    seeder:
#        build: src/seeder
#        environment:
#            TARGET_HOST: db
#            TARGET_PORT: 1521
