services:
    db:
        # https://hub.docker.com/r/gvenzl/oracle-xe
        image: gvenzl/oracle-xe:11
        ports:
            - "1521:1521"
        environment:
          ORACLE_RANDOM_PASSWORD: true
          APP_USER: ${DB_USERNAME}
          APP_USER_PASSWORD: ${DB_PASSWORD}
        volumes:
            - oracle-data:/u01/app/oracle/oradata

volumes:
    oracle-data: